name: CMake

on: [push, pull_request]

jobs:

  skip_check:

    name: Skip Check
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'outdated_runs'
          paths_ignore: '["**.md"]'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: make

    # TODO: Remove ! just for testing
    - name: Sleep 40
      run: sleep 40

    - name: Test
      run: ctest

